### ISSUE TITLE
Canvas sizing 

### ISSUE THREAD

**Issue by rmagee88** [graffiome/graffiome#12]
Figure out how to have variable size canvases to match window size (up to 16k x 16k)

**Comment by mrblueblue** [comment]
Canvas currently matches window size, but cannot fill the entire page if it requires scrolling.

I haven't figured out a way for it to stretch the entire page.

Let me know if you guys have any suggestions for doing this (short of appending multiple canvas elements onto the page...)

**Comment by wettowelreactor** [comment]
@mrblueblue is this safe to close?

**Comment by mrblueblue** [comment]
@wettowelreactor we can close this one.
