### ISSUE TITLE
User canvas remains on page after logout

### ISSUE THREAD

**Issue by mrblueblue** [graffiome/graffiome#36]
Currently, when the user logs out, the canvas elements still remain on the page.

It'd be a better UX if all canvas elements are removed on logout.

I've added a message listener to the content-script. If it received a message {logout:true}, it will remove all canvas elements.

Can someone add a send message event in the main.js?

**Comment by wettowelreactor** [comment]
I'll take care of it. 

--Camille Roussel

**Comment by mrblueblue** [comment]
fixed
